spring:
  application:
    name: infohub
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/InfoHub
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
